### PR TITLE
move from get to post

### PR DESCRIPTION
**Pull request by antoine-lemaitre**
Hi there!

Get api for oauth/token is deprecated: https://us.forums.blizzard.com/en/blizzard/t/http-get-deprecated-for-oauthtoken-endpoint/15232

I propose those little changes to use the post api.

Bests

### CODE REVIEW

**Comment by antoine-lemaitre** [comment]
Hell yeah

**Review by pizzadudez — APPROVED** [review]

**Comment by antoine-lemaitre** [comment]
@lockwooddev I would be very glad if you got time to review it :)

**Comment by antoine-lemaitre** [comment]
@lockwooddev if you are in this area :)

**Comment by antoine-lemaitre** [comment]
@lockwooddev : thank you! Are you considering making another release in the near future?

**Comment by lockwooddev** [comment]
Sorry for the delays, but life has been busy. I do plan a release, but I first would have to go over all the endpoints to make sure they didn't change everything once again :P
In the meantime I suggest you pip install the specific commit hash.

**Pull request merged**
