### PR TITLE
Add profile api

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by lockwooddev** [comment]
#12 I fixed your tests and it should be working now for you

**Comment by Soulofdestiny** [comment]
cool thanks - I will close this one then and you can go with #12 ?

**Comment by lockwooddev** [comment]
Yes let's do that. I will merge it and bump the version.

**Comment by lockwooddev** [comment]
2.3.0 is now available on pypi. Thank you for contributing this missing feature :)

https://pypi.org/project/python-wowapi/2.3.0/

**Pull request closed without merging**
